<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["exhibitors/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["exhibitors/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Ragionesociale</th>
            <th>Cap</th>
            <th>Citta</th>
            <th>Provincia</th>
            <th>Telefono</th>
            <th>Emailaziendale</th>
            <th>Partitaiva</th>
            <th>Codicefiscale</th>
            <th>Referentenome</th>
            <th>Referentetelefono</th>
            <th>Referenteemail</th>
            <th>Prodottiesposti</th>
            <th>Fasciadiprezzo</th>
            <th>Numerocoespositore</th>
            <th>Nomecoespositore</th>
            <th>Catalogonome</th>
            <th>Catalogoindirizzo</th>
            <th>Catalogocap</th>
            <th>Catalogocitta</th>
            <th>Catalogoprovincia</th>
            <th>Catalogotelefono</th>
            <th>Catalogoemail</th>
            <th>Catalogositoweb</th>
            <th>Catalogofacebook</th>
            <th>Catalogoinstagram</th>
            <th>Catalogotwitter</th>
            <th>Catalogodescrizione</th>
            <th>Interventoprogrammaculturale</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $exhibitor): ?>
            <tr>
                <td><?php echo $exhibitor->id ?></td>
            <td><?php echo $exhibitor->ragionesociale ?></td>
            <td><?php echo $exhibitor->cap ?></td>
            <td><?php echo $exhibitor->citta ?></td>
            <td><?php echo $exhibitor->provincia ?></td>
            <td><?php echo $exhibitor->telefono ?></td>
            <td><?php echo $exhibitor->emailaziendale ?></td>
            <td><?php echo $exhibitor->partitaiva ?></td>
            <td><?php echo $exhibitor->codicefiscale ?></td>
            <td><?php echo $exhibitor->referentenome ?></td>
            <td><?php echo $exhibitor->referentetelefono ?></td>
            <td><?php echo $exhibitor->referenteemail ?></td>
            <td><?php echo $exhibitor->prodottiesposti ?></td>
            <td><?php echo $exhibitor->fasciadiprezzo ?></td>
            <td><?php echo $exhibitor->numerocoespositore ?></td>
            <td><?php echo $exhibitor->nomecoespositore ?></td>
            <td><?php echo $exhibitor->catalogonome ?></td>
            <td><?php echo $exhibitor->catalogoindirizzo ?></td>
            <td><?php echo $exhibitor->catalogocap ?></td>
            <td><?php echo $exhibitor->catalogocitta ?></td>
            <td><?php echo $exhibitor->catalogoprovincia ?></td>
            <td><?php echo $exhibitor->catalogotelefono ?></td>
            <td><?php echo $exhibitor->catalogoemail ?></td>
            <td><?php echo $exhibitor->catalogositoweb ?></td>
            <td><?php echo $exhibitor->catalogofacebook ?></td>
            <td><?php echo $exhibitor->catalogoinstagram ?></td>
            <td><?php echo $exhibitor->catalogotwitter ?></td>
            <td><?php echo $exhibitor->catalogodescrizione ?></td>
            <td><?php echo $exhibitor->interventoprogrammaculturale ?></td>

                <td><?php echo $this->tag->linkTo(["exhibitors/edit/" . $exhibitor->id, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["exhibitors/delete/" . $exhibitor->id, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("exhibitors/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("exhibitors/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("exhibitors/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("exhibitors/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
